knowledgeGraph(entityType: "healthcareProfessional") {
    id
    name
    description
    slug @multilanguage(locales: ["en", "es", "de"])
    c_optionField(format: DISPLAY)
    paymentOptions: optionList(field: "paymentOptions") {
      value
      displayName
      selected
    }
    c_specialties {
      name
    }
    rel_doctorHospital(role: "provider") {
      hours
      location {
        name
      }
    }
    listings @keyBy(field: "publisher") {
        url
    }
    reviewsByPublisher(publishers: ["googleMyBusiness", "facebook"], last: 20) {
        publisher {
            reviewId
            authorName
            content
            reviewUrl
        }
    }
}